
//#############################################################################
//# Makefile for building: pro1
//# Generated by qmake (3.0) (Qt 5.4.1)
//# Project:  pro1.pro
//# Template: app
//# Command: qmake -spec linux-g++ CONFIG+=debug -o Makefile pro1.pro
//#############################################################################

#include <QCoreApplication>
#include <QApplication>

#include <QtCore>

#include <QWidget>

#include <QPushButton>

#include "imageview.h"

int main(int argc, char *argv[])
{
    QApplication app(argc, argv);

    qDebug()<<"start\n";

    ImageView mImageView;

    QGuiApplication::setApplicationDisplayName(ImageView::tr("Image Viewer"));
    QCommandLineParser commandLineParser;
    commandLineParser.addHelpOption();
    commandLineParser.addPositionalArgument("[file]",ImageView::tr(
                                                "Image file to open."));

    commandLineParser.process(QCoreApplication::arguments());

    mImageView.show();

    qDebug()<<"quit\n";

    return app.exec();
}
